### ISSUE TITLE
PANIC: thread 'tokio-runtime-worker' panicked at livekit/src/rtc_engine/rtc_session.rs:595:43:

### ISSUE THREAD

**Issue by ryanleecode** [livekit/rust-sdks#450]
```
thread 'tokio-runtime-worker' panicked at livekit/src/rtc_engine/rtc_session.rs:595:43:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /workspace/livekit-runtime/src/tokio.rs:39:46:
Tasks should not panic: JoinError::Panic(Id(175), ...)
```

This is happening when i call `sendChat` from react

**Comment by ryanleecode** [comment]
i was able to fix thsi by downgrading `@livekit/components-react` back to 2.6.0. it seems like there is issue with new chat api.

https://github.com/livekit/components-js/releases/tag/%40livekit%2Fcomponents-react%402.6.1

cc @lukasIO

**Comment by ryanleecode** [comment]
this is my `requirements.txt`

```
livekit==0.17.1
livekit-agents==0.9.1
livekit-api==0.7.0
livekit-plugins-deepgram==0.6.7
livekit-plugins-openai==0.8.5
livekit-plugins-rag==0.2.2
livekit-plugins-silero==0.6.4
llama-index-postprocessor-cohere-rerank==0.2.1
livekit-protocol==0.6.0
llama-index==0.11.14
python-dotenv~=1.0
pydantic==2.9.2
msgpack==1.1.0
dacite==1.8.1
```
